function figData=Online_LickPlot(action,trialSequence,figData,outcome,licks)
%This function initializes ("ini") or updates ("update") a figure to monitor online the trial sequence and the lick events. 
%Initialization requiers the "trialSequence" and the parameters of the trials contained in the "S.TrialsMatrix". 
%"licks" and "outcome" arguments are used to update the subplot for trials
%"outcome" and "licks" arguments are generated by "Online_LickEvents" function.
%
%The output structure is used to update the plot and contains :
%figData.figPlot        :handles the figure properties
%       .trialusbplot   :handles the subplot for trial (axes)
%       .curTrialplot   :handles the current trial plot (a line)
%       .trialsplot     :handles the plots for eachtrials (data)
%       .licksubplot    :handles the subplot for lick (axes)
%       .lickplot       :handles the plot for lick (data)
%
%function written by Quentin for CuedReinforcers bpod protocol

global BpodSystem S

plotSpan=20.5;  %plotting window
MS_trial=5;     %marker size for trial
MS_licks=2;     %marker size for lick
maxy=100;       %y axe for licks
ystep=25;       %y axe for licks

minx=S.GUI.TimeMin;
maxx=S.GUI.TimeMax;
xstep=1;    xtickvalues=minx:xstep:maxx;

switch action
    case 'ini'
%%Close pre-existing plot and test parameters
try
    close 'Online Lick Plot';
end
%% Create Figure
ScrSze=get(0,'ScreenSize');
FigSze=[1 ScrSze(2)+40 ScrSze(3)*1/3 ScrSze(4)-120];
figPlot=figure('Name','Online Lick Plot','Position',FigSze, 'numbertitle','off');
hold on
ProtoSummary=sprintf('%s : %s -- %s - %s',...
    date, BpodSystem.GUIData.SubjectName, ...
    BpodSystem.GUIData.ProtocolName, S.Names.Phase{S.GUI.Phase});
MyBox = uicontrol('style','text');
set(MyBox,'String',ProtoSummary, 'Position',[10,1,400,20]);

%% Trial plot
trialsubplot=subplot(4,2,[1 2]);
hold on
%Specify legend and axes
l1=plot(-20,-20,'ko','MarkerSize',MS_trial); %circle legend, ie reward
l2=plot(-20,-20,'ks','MarkerSize',MS_trial); %square legend, ie omission
l3=plot(-20,-20,'kd','MarkerSize',MS_trial); %diamond legend, ie Large
l4=plot(-20,-20,'ko','MarkerFaceColor','g','MarkerSize',MS_trial); %green legend, ie hit
l5=plot(-20,-20,'ko','MarkerFaceColor','r','MarkerSize',MS_trial); %red legend, ie missed

title('Trials outcome - Collected Water=0');
xlabel('Trial Number');
ylabel('Cue type')

%Generates and handles plots for each trials and a current trial plot
curTrialplot=plot([1 1],[0 0.5+max(S.TrialsMatrix(:,3))],'-b');
for i=1:length(trialSequence)
    trialsPlot(i)=plot(i,S.TrialsMatrix(trialSequence(i),3),'LineStyle','none','marker',char(S.TrialsMatrix(trialSequence(i),7)),'MarkerFaceColor','b', 'MarkerEdgeColor','k','MarkerSize',MS_trial);
end
hold off
set(trialsubplot,'XLim',[3-plotSpan 3+plotSpan],'YLim',[0.5 0.5+max(S.TrialsMatrix(:,3))],'YDir','reverse','YTick',1:max(S.TrialsMatrix(:,3)));
legend([l1 l2 l3 l4 l5],'Reward','Omission','Punishment','Hit','Missed','Location','east');
legend('boxoff');
%% Lick plot
%PlotParameters
labely='Trial number';
miny=0;                             ytickvalues=miny:ystep:maxy;
labelx='Time from reward / cue (sec)';
subplotTitles=S.TrialsNames;
for i=1:S.TrialsMatrix(end,1)
    subplotTitles{i}=sprintf('%s - cue # %.0d',subplotTitles{i},S.TrialsMatrix(i,3));
end
%Subplot
for i=1:6
    licksubplot(i)=subplot(4,2,i+2);
    hold on
    rewplot(i)=plot([0 0],[-5,maxy],'-r');
    trackingplot(i)=plot([S.GUI.TimeMin S.GUI.TimeMax],[0 0],'-b');
    lickplot(i)=plot([0 0],[1,500],'sk','MarkerSize',MS_licks,'MarkerFaceColor','k');
    set(lickplot(i), 'XData',[],'YData',[]);
    title(subplotTitles(i));
    xlabel(labelx); 
    ylabel(labely);
    set(licksubplot(i),'XLim',[minx maxx],'XTick',xtickvalues,'YLim',[miny maxy],'YTick',ytickvalues,'YDir', 'reverse');
end

set(licksubplot(1),'XLabel',[]);
set(licksubplot(2),'XLabel',[],'YLabel',[]);
set(licksubplot(3),'XLabel',[]);
set(licksubplot(4),'XLabel',[],'YLabel',[])
%set(licksubplot(5),'XLabel',labelx,'YLabel',labely);
set(licksubplot(6),'YLabel',[]);

%Save the figure properties
figData.fig=figPlot;
figData.trialsubplot=trialsubplot;
figData.trialsplot=trialsPlot;
figData.curTrialplot=curTrialplot;
figData.licksubplot=licksubplot;
figData.lickplot=lickplot;
figData.trackingplot=trackingplot;
figData.water=0;

    case 'update'
currentTrial=length(BpodSystem.Data.TrialTypes);
currentTrialType=BpodSystem.Data.TrialTypes(end);
%% Trial Plot
%Change color of the last trial marker according to the oucome
set(figData.trialsplot(currentTrial),'MarkerFaceColor',outcome);
%Move the current trial plot and the plotting window
set(figData.trialsubplot, 'XLim',[currentTrial-plotSpan+2 currentTrial+plotSpan+2]);
set(figData.curTrialplot,'Xdata', [currentTrial+1 currentTrial+1]);
if sum(licks>0 & licks<2)>3 && S.Valve==S.GUI.RewardValve
    figData.water=figData.water+5;
    figure(figData.fig);
    subplot(4,2,[1 2]);
    title(sprintf('Trials outcome - Water = %.0d ul',figData.water));
end

        if currentTrialType<=6
%% LickPlot
%Extract the previous data from the plot
previous_xdata=get(figData.lickplot(currentTrialType),'XData');   %lick time
previous_ydata=get(figData.lickplot(currentTrialType),'YData');    %trial number

%initialize the first raster
if isempty(previous_ydata)
    trialTypeCount=1; 
else
    trialTypeCount=max(previous_ydata)+1;
end 

%Update the figure with the new licking data
if trialTypeCount>maxy
    set(figData.licksubplot(currenttrialType),'YLim',[0 trialTypeCount]);
end
updated_xdata=[previous_xdata licks];
newydata=linspace(trialTypeCount,trialTypeCount,size(licks,2));
updated_ydata=[previous_ydata newydata];
set(figData.lickplot(currentTrialType),'XData',updated_xdata,'YData',updated_ydata);
set(figData.trackingplot(currentTrialType),'YData',[trialTypeCount trialTypeCount]);
        end
%% Update GUI plot parameters
for i=1:6       
        set(figData.licksubplot(i),'XLim',[minx maxx],'XTick',xtickvalues);
end
end
end